const express = require('express')
const bodyParser = require('body-parser')
var cors = require('cors')
var app = express()
app.use(cors())
app.use(bodyParser.urlencoded({ extended: false }))
app.use(bodyParser.json())
let login = require('./routes/login')
let users = require('./routes/users')
let articles = require('./routes/articles')
app.use('/login', login)
app.use('/users', users)
app.use('/articles', articles)
app.listen(4000, () => {
  console.log('Ready port 4000')
})